version: '3.7'
services:
  app:
    build: .
    command: >
      sh -c "pytest -v &&
      bandit -r -x test_main ."
    volumes:
      - ./app:/app
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
